-- Tables
-- lookupitem
-- lookupset
-- property
-- nodetype
-- property_group
-- nodetype_property
-- store
-- principal_group
-- nodetype_bfcf13dec59e4179bbc8168111d8980a (EDDA Form)
-- nodetype_i82db307b15646a29e43a6ba28971801 (DDA Form)
-- nodetype_d4fb23bf1402454c899d7c9ed7be14d2 (eMandate file received Log)
-- nodetype_fb160c57f6c849e1b1a3b3a40901b196 (merchant code)
-- nodetype_d967deb0a4c44739ac74466f7988d104 (DDA Folder)
-- profile
-- bankmastertable (from saffron)
-- container_containee
-- esign_wflow
-- record_node
-- hold_node
-- hold
-- recent_container
-- ftextindex
-- evt_based_notification
-- node_event
-- object_event

SET DATABASE SQL REGULAR NAMES FALSE;

CREATE TYPE  TEXT AS VARCHAR(1000000);

CREATE TABLE lookupitem (
    uid character(32) NOT NULL,
    lookupset_uid character(32) NOT NULL,
    code character varying(10) NOT NULL,
    val character varying(50) NOT NULL,
    description text
);

CREATE TABLE lookupset (
    uid character(32) NOT NULL,
    name character varying(255) NOT NULL,
    description text
);

CREATE TABLE property (
    uid character(32) NOT NULL,
    name character varying(100) NOT NULL,
    property_type integer NOT NULL,
    length integer NOT NULL,
    decimals integer NOT NULL,
    refnodetypeid character(32),
    refmultivalue smallint,
    acl_uid character(32),
    semantics smallint,
    maskre character varying(255),
    min_date_value timestamp without time zone,
    max_date_value timestamp without time zone,
    min_int_value integer,
    max_int_value integer,
    min_decimal_value numeric(31,5),
    max_decimal_value numeric(31,5),
    groups_only smallint,
    non_groups_only smallint,
    must_be_member_of character(32),
    must_be_container smallint,
    lookupset_uid character(32),
    using_lookupset smallint DEFAULT 0 NOT NULL,
    allow_non_matching_values smallint DEFAULT 0 NOT NULL,
    apply_to_principal smallint DEFAULT 0 NOT NULL
);

CREATE TABLE nodetype (
    uid character(32) NOT NULL,
    name character varying(50) NOT NULL,
    description character varying(255),
    store_uid character(32),
    acl_uid character(32),
    apply_node_acl_filter smallint DEFAULT 0 NOT NULL,
    apply_nodetype_default_acl_filter smallint DEFAULT 0 NOT NULL,
    apply_owner_filter smallint DEFAULT 0 NOT NULL,
    apply_classification_default_acl_filter smallint DEFAULT 0 NOT NULL,
    apply_container_based_filter smallint DEFAULT 0 NOT NULL,
    is_container smallint DEFAULT 0 NOT NULL,
    level smallint DEFAULT 1 NOT NULL,
    record_numbering_method smallint,
    enclosure_number_prefix character varying(3),
    enclosure_number_suffix character varying(3),
    current_record_year integer,
    reset_record_number_at_year_end smallint DEFAULT 0 NOT NULL,
    next_record_number integer,
    record_number_pattern character varying(50),
    init_record_number integer DEFAULT 1,
    number_pattern_increment integer DEFAULT 1 NOT NULL,
    enclosure_number_max_digits integer DEFAULT 3 NOT NULL,
    default_acl_uid character(32),
    default_security_level_uid character(32),
    default_retention_schedule_uid character(32),
    is_metadata_text_indexed smallint DEFAULT 0 NOT NULL,
    is_content_text_indexed smallint DEFAULT 0 NOT NULL,
    titling_method smallint DEFAULT 11 NOT NULL,
    can_attach_content smallint DEFAULT 0 NOT NULL,
    content_mandatory smallint DEFAULT 0 NOT NULL,
    is_shreddable smallint DEFAULT 0 NOT NULL,
    autoexec_script text,
    titlealias character varying(255),
    icon binary,
    description_alias character varying(255),
    notes_alias character varying(255),
    record_number_alias character varying(255),
    barcode_alias character varying(255),
    container_alias character varying(255),
    external_barcode_alias character varying(255),
    enclosure_number_alias character varying(255),
    classification_alias character varying(255),
    secondary_classification_alias character varying(255),
    tertiary_classification_alias character varying(255),
    date_registered_alias character varying(255),
    creator_name_alias character varying(255),
    creator_username_alias character varying(255),
    master_alias character varying(255),
    date_of_last_enclosure_alias character varying(255),
    date_enclosed_alias character varying(255),
    date_finalized_alias character varying(255),
    assignee_alias character varying(255),
    home_alias character varying(255),
    owner_alias character varying(255),
    disposition_status_alias character varying(255),
    external_uid_alias character varying(255),
    integrity_check_alias character varying(255),
    finalized_alias character varying(255),
    is_hybrid_alias character varying(255),
    retention_schedule_alias character varying(255),
    security_level_alias character varying(255),
    date_last_modified_alias character varying(255),
    date_last_modified_of_contents_alias character varying(255),
    client_alias character varying(255),
    combined_title_alias character varying(255),
    mime_type_alias character varying(255),
    date_closed_alias character varying(255),
    num_digits_enclosure_number smallint DEFAULT 3 NOT NULL,
    apply_autoexec_scripting smallint DEFAULT 0 NOT NULL,
    uncompressed_record_number_alias character varying(255),
    opened_temporarily_alias character varying(255),
    date_created_alias character varying(255),
    author_alias character varying(255),
    batch_id_alias character varying(255),
    date_archived_alias character varying(255),
    date_made_inactive_alias character varying(255),
    apply_content_template smallint DEFAULT 0 NOT NULL,
    content_template_node_uid character(65),
    copy_content_template_on_create smallint DEFAULT 0 NOT NULL,
    copy_content_template_on_update smallint DEFAULT 0 NOT NULL,
    content_template_on_update_behaviour smallint DEFAULT 1 NOT NULL,
    launch_activity_on_node_create smallint DEFAULT 0 NOT NULL,
    activity_name character varying(50),
    apply_content_conversion smallint DEFAULT 0 NOT NULL,
    conversion_format character varying(10),
    default_auto_finalize smallint DEFAULT 0 NOT NULL,
    record_class_alias character varying(255),
    default_record_class integer DEFAULT 0 NOT NULL,
    is_voluming_enabled smallint DEFAULT 0 NOT NULL,
    is_auto_close_volume smallint DEFAULT 0 NOT NULL,
    is_close_volume_after_exceed_max_content smallint DEFAULT 0 NOT NULL,
    is_close_volume_on_particular_date smallint DEFAULT 0 NOT NULL,
    is_close_volume_on_triggered_event smallint DEFAULT 0 NOT NULL,
    is_auto_open_volume_after_exceed_max_content smallint DEFAULT 0 NOT NULL,
    is_auto_open_volume_on_particular_date smallint DEFAULT 0 NOT NULL,
    is_auto_open_volume_on_triggered_event smallint DEFAULT 0 NOT NULL,
    volume_max_content integer DEFAULT 1,
    volume_closing_date timestamp without time zone,
    volume_triggered_event integer DEFAULT 0,
    volume_triggered_event_type integer DEFAULT 0,
    volume_triggered_event_duration integer DEFAULT 1,
    volume_separator character varying(5),
    num_of_digits_for_volume_number integer DEFAULT 3 NOT NULL,
    volume_triggered_event_property_uid character(32),
    record_event_setting integer DEFAULT 63 NOT NULL,
    is_auto_update_security_level smallint DEFAULT 0 NOT NULL,
    is_auto_update_security_level_on_particular_date smallint DEFAULT 0 NOT NULL,
    security_level_trigger_date timestamp without time zone,
    is_update_security_level_on_triggered_event smallint DEFAULT 0 NOT NULL,
    security_level_triggered_event integer DEFAULT 0,
    security_level_triggered_event_type integer DEFAULT 0,
    security_level_triggered_event_duration integer DEFAULT 1,
    security_level_triggered_event_property character(32),
    auto_update_security_level_id character(32),
    hybrid_remarks_alias character varying(255),
    is_declassify_alias text,
    enforce_single_creation_in_a_workflow smallint DEFAULT 0 NOT NULL,
    check_in_as_new_version smallint DEFAULT 0 NOT NULL,
    check_in_as_override_previous_content smallint DEFAULT 0 NOT NULL,
    is_imported smallint DEFAULT 0 NOT NULL,
    can_show_tab smallint DEFAULT 1 NOT NULL,
    can_show_alt_container smallint DEFAULT 1 NOT NULL,
    can_show_rel_record smallint DEFAULT 1 NOT NULL,
    can_show_retention smallint DEFAULT 1 NOT NULL
);

CREATE TABLE property_group (
    nodetype_uid character(32) NOT NULL,
    name character varying(50) NOT NULL,
    group_order integer NOT NULL
);

CREATE TABLE nodetype_property (
    nodetype_uid character(32) NOT NULL,
    property_uid character(32) NOT NULL,
    alias character varying(255) DEFAULT '',
    is_mandatory smallint DEFAULT 0 NOT NULL,
    is_readonly smallint DEFAULT 0 NOT NULL,
    property_group_name character varying(50),
    property_order integer,
    default_value text
);

CREATE TABLE nodetype_attribute (
    nodetype_uid character(32) NOT NULL,
    attribute_no smallint NOT NULL,
    group_name character varying(50),
    _order integer
);

CREATE TABLE store (
    uid character(32) NOT NULL,
    name character varying(50) NOT NULL,
    store_type character(3) NOT NULL,
    uri character varying(255) NOT NULL,
    acl_uid character(32),
    readonly smallint DEFAULT 0 NOT NULL,
    encryption smallint DEFAULT 0 NOT NULL
);

CREATE TABLE principal (
    uid character(32) NOT NULL,
    name character varying(255) NOT NULL,
    extid character varying(50),
    username character varying(50),
    password character varying(255),
    isgroup smallint DEFAULT 0 NOT NULL,
    acl_uid character(32),
    security_level_uid character(32),
    isinternal smallint DEFAULT 0 NOT NULL,
    issuspended smallint DEFAULT 0 NOT NULL,
    gender smallint DEFAULT 3 NOT NULL,
    email character varying(255),
    profile_uid character(32),
    canlogin smallint DEFAULT 0 NOT NULL,
    active_from timestamp without time zone,
    active_to timestamp without time zone,
    date_registered timestamp without time zone,
    barcode character varying(50),
    external_barcode character varying(50),
    ptype smallint DEFAULT 0 NOT NULL,
    date_last_modified_of_password timestamp without time zone,
    loginmessage text,
    address text,
    ic_passport_no character varying(32),
    date_of_birth timestamp without time zone,
    nationality character varying(50),
    business_occupation character varying(255),
    phone_number character varying(20),
    mobile_phone character varying(20)
);

CREATE TABLE principal_group (
    principal_uid character(32) NOT NULL,
    group_uid character(32) NOT NULL
);

CREATE TABLE nodetype_bfcf13dec59e4179bbc8168111d8980a (
    uid character(65) NOT NULL,
    acl_uid character(32),
    owner_uid character(32),
    classification_uid character(32),
    secondary_classification_uid character(32),
    tertiary_classification_uid character(32),
    record_number character varying(100),
    retention_schedule_uid character(32),
    hold_uid character(32),
    disposition_status integer,
    title character varying(255),
    combined_title text,
    description text,
    date_registered timestamp without time zone,
    creator_name character varying(255),
    creator_username character varying(255),
    notes text,
    home_uid character(32),
    assignee_uid character(32),
    is_finalized smallint,
    is_hybrid smallint DEFAULT 0,
    date_finalized timestamp without time zone,
    barcode character varying(50),
    external_barcode character varying(50),
    external_uid character varying(50),
    integrity_check text,
    security_level_uid character(32),
    date_last_modified timestamp without time zone,
    date_last_modified_of_contents timestamp without time zone,
    client_uid character(32),
    date_closed timestamp without time zone,
    next_enclosure_number integer DEFAULT 1 NOT NULL,
    enclosure_number_increment integer DEFAULT 1 NOT NULL,
    uncompressed_record_number character varying(100),
    security_based_on_container smallint DEFAULT 0,
    bypass_referenced_acls smallint DEFAULT 0,
    opened_temporarily smallint DEFAULT 0,
    date_created timestamp without time zone,
    author character varying(255),
    batch_id character varying(40),
    date_archived timestamp without time zone,
    date_made_inactive timestamp without time zone,
    date_of_last_enclosure timestamp without time zone,
    date_enclosed timestamp without time zone,
    record_class integer DEFAULT 0 NOT NULL,
    container_record_number character varying(50),
    classification_full_number character varying(255),
    secondary_classification_full_number character varying(255),
    tertiary_classification_full_number character varying(255),
    assignee_name character varying(255),
    home_name character varying(255),
    owner_name character varying(255),
    retention_schedule_number character varying(100),
    security_level_number smallint,
    client_name character varying(255),
    is_container_removed_on_ret_trig smallint DEFAULT 0,
    is_set_home_on_container_ret_trig smallint DEFAULT 0,
    retention_schedule_new_home character(32),
    is_misfiled smallint DEFAULT 0,
    master_uid character(65),
    hybrid_remarks text,
    date_last_modified_of_security_level timestamp without time zone,
    is_declassify smallint DEFAULT 0,
    is_imported smallint DEFAULT 0,
    enforce_single_creation_in_a_workflow smallint DEFAULT 0 NOT NULL,
    check_in_as_new_version smallint DEFAULT 0 NOT NULL,
    check_in_as_override_previous_content smallint DEFAULT 0 NOT NULL,
    is_declassify_alias text,
    is_auto_update_security_level smallint DEFAULT 0 NOT NULL,
    is_auto_update_security_level_on_particular_date smallint DEFAULT 0 NOT NULL,
    security_level_trigger_date timestamp without time zone,
    is_update_security_level_on_triggered_event smallint DEFAULT 0 NOT NULL,
    security_level_triggered_event integer DEFAULT 0,
    security_level_triggered_event_type integer DEFAULT 0,
    security_level_triggered_event_duration integer DEFAULT 0,
    security_level_triggered_event_property character(32),
    auto_update_security_level_id character(32),
    g8a113b4b0854de6bb862a7bf714431d character varying(100),
    b4ccea01158440449c83dacca40771d6 character varying(100),
    gb4022b9cefc4b07b9958b8c73b2a17c character varying(95),
    adfaa188a81e447fbde0461021f43349 character varying(100),
    f1da51d24ef24be2979bda91ba8d59ac character varying(21),
    h12a967b55434049b7ad59b17fc6a596 character varying(20),
    dccdb8734f2244f3b5cb1b3cf9aa6a10 character varying(4),
    f80092a495454a4ab5a50d32cf6e8b74 character varying(20),
    h7e1bec9fed94c0d8deaeb02b94b48bb character varying(210),
    c94b3507b2094211af5c15b9674e24da character varying(20),
    e48d64d8cab749d2aa11569bd527b746 integer,
    h5d3080119084691906659f8204575b5 character varying(100),
    i80ca2be661f4a47a5e18d1f4704dc40 timestamp without time zone,
    ebe110a85e424744a703ee31fcb13246 timestamp without time zone,
    a6ed722bf65043f9a3b0d602ff110b84 timestamp without time zone,
    h1bcd8ce6f7443538eda334170f71cc2 character varying(10),
    bd3fe6ad0f694c88b811e295cd80c2db character varying(35),
    d26ba65d85c7415e8c3a1d7b9b5f4055 timestamp without time zone,
    d1565a63d85847b0b79faf2efc982685 character varying(100),
    ce3d0055173648f391e01be93dd7098e character varying(100),
    h99d1f8650d448fa9e3b43a9323c12bf text,
    b5d25c12c739407b8b298f1c51170a4a character varying(100),
    cd2bfcb5c3e2441b915609538f9fb286 character varying(100),
    bb55a2f92921452694f59d8a8a1326d5 character varying(100),
    ca1f972f4de3489ab22a01969d48cf87 character varying(100),
    j47f50ff755140a4aca912843f4d34b5 character varying(100),
    f3187fb157ea48aa951e3c2b99dc0f7b character varying(100),
    e261a9b74bf34bfbb2a2961456ebe4d0 character varying(100),
    jeb5a5a44f584ced918daa63fc516d3a text,
    g01690cbd8cc49199cfa07bd592d8019 text,
    da763089b5a74afbb02caf6260fbd5f1 text,
    ddaa3d5555544e4189b778b33378a068 text,
    f0d32c9c463943beabb62aee111dedd7 character varying(100),
    cbf0d79ce6174a4d9d51253ff7378f73 character varying(100),
    c774ea5e257840519a9e288f59b9b363 character(32),
    cc2480e3fe9e4e65bd4911b254055033 character varying(100),
    b403ff0d8f8f4246b38b60374141e5bd character varying(100),
    dd34eae45f8b4064aef0cdb83693b860 character(32),
    f698d75dbf9246299dfc500287e26db3 character varying(100),
    bc9c226e4b924d669888ee61a64403ef character varying(100),
    a2ab318732c646fcb3c53c659b102913 character(32),
    d9b6a0e29ad645c5a7b72d93d0fe1d47 character varying(100),
    e10ba09257a94839884fc98626b906dc character varying(100),
    heed7bff76b5478eb40f0a27e48d2d96 character(32),
    gfe84d6fa81848d19f711815b8a3e22f numeric(18,2),
    cdabda50f9404a77a4c22dd774a6c838 character varying(100),
    h958dbfaeae545e29e3f79e4d43f7b5f character varying(100),
    fa440ecc98964ea5826a40ead969576b character varying(100),
    ca7e88f2c8594a12bb9af8738bab5295 character varying(100),
    f7c60449b52448ad865893ad329463d6 character varying(100),
    cb719c02dac1405b9f36832b643a3238 numeric(10,2),
    h45ca6122be44564880af16c63d4b03a numeric(16,2)
);

CREATE TABLE nodetype_i82db307b15646a29e43a6ba28971801 (
    uid character(65) NOT NULL,
    acl_uid character(32),
    owner_uid character(32),
    classification_uid character(32),
    secondary_classification_uid character(32),
    tertiary_classification_uid character(32),
    record_number character varying(50),
    retention_schedule_uid character(32),
    hold_uid character(32),
    disposition_status integer,
    title character varying(255),
    combined_title text,
    description text,
    date_registered timestamp without time zone,
    creator_name character varying(255),
    creator_username character varying(255),
    notes text,
    home_uid character(32),
    assignee_uid character(32),
    is_finalized smallint,
    is_hybrid smallint DEFAULT 0,
    date_finalized timestamp without time zone,
    barcode character varying(50),
    external_barcode character varying(50),
    external_uid character varying(50),
    integrity_check text,
    security_level_uid character(32),
    date_last_modified timestamp without time zone,
    date_last_modified_of_contents timestamp without time zone,
    client_uid character(32),
    date_closed timestamp without time zone,
    next_enclosure_number integer DEFAULT 1 NOT NULL,
    enclosure_number_increment integer DEFAULT 1 NOT NULL,
    uncompressed_record_number character varying(50),
    security_based_on_container smallint DEFAULT 0,
    bypass_referenced_acls smallint DEFAULT 0,
    opened_temporarily smallint DEFAULT 0,
    date_created timestamp without time zone,
    author character varying(255),
    batch_id character varying(40),
    date_archived timestamp without time zone,
    date_made_inactive timestamp without time zone,
    date_of_last_enclosure timestamp without time zone,
    date_enclosed timestamp without time zone,
    record_class integer DEFAULT 0 NOT NULL,
    container_record_number character varying(50),
    classification_full_number character varying(255),
    secondary_classification_full_number character varying(255),
    tertiary_classification_full_number character varying(255),
    assignee_name character varying(255),
    home_name character varying(255),
    owner_name character varying(255),
    retention_schedule_number character varying(100),
    security_level_number smallint,
    client_name character varying(255),
    is_container_removed_on_ret_trig smallint DEFAULT 0,
    is_set_home_on_container_ret_trig smallint DEFAULT 0,
    retention_schedule_new_home character(32),
    is_misfiled smallint DEFAULT 0,
    master_uid character(65),
    hybrid_remarks text,
    i80ca2be661f4a47a5e18d1f4704dc40 timestamp without time zone,
    b5d25c12c739407b8b298f1c51170a4a character varying(100),
    d26ba65d85c7415e8c3a1d7b9b5f4055 timestamp without time zone,
    adfaa188a81e447fbde0461021f43349 character varying(100),
    e48d64d8cab749d2aa11569bd527b746 integer,
    h5d3080119084691906659f8204575b5 character varying(100),
    h1bcd8ce6f7443538eda334170f71cc2 character varying(10),
    ce3d0055173648f391e01be93dd7098e character varying(100),
    b4ccea01158440449c83dacca40771d6 character varying(100),
    f3187fb157ea48aa951e3c2b99dc0f7b character varying(100),
    date_last_modified_of_security_level timestamp without time zone,
    g8a113b4b0854de6bb862a7bf714431d character varying(100),
    is_declassify smallint DEFAULT 0,
    is_auto_update_security_level smallint DEFAULT 0 NOT NULL,
    is_auto_update_security_level_on_particular_date smallint DEFAULT 0 NOT NULL,
    security_level_trigger_date timestamp without time zone,
    is_update_security_level_on_triggered_event smallint DEFAULT 0 NOT NULL,
    security_level_triggered_event integer DEFAULT 0,
    security_level_triggered_event_type integer DEFAULT 0,
    security_level_triggered_event_duration integer DEFAULT 1,
    security_level_triggered_event_property character(32),
    auto_update_security_level_id character(32),
    dccdb8734f2244f3b5cb1b3cf9aa6a10 character varying(4),
    d1565a63d85847b0b79faf2efc982685 character varying(100),
    ebe110a85e424744a703ee31fcb13246 timestamp without time zone,
    h99d1f8650d448fa9e3b43a9323c12bf text,
    j47f50ff755140a4aca912843f4d34b5 character varying(100),
    a6ed722bf65043f9a3b0d602ff110b84 timestamp without time zone,
    enforce_single_creation_in_a_workflow smallint DEFAULT 0 NOT NULL,
    h12a967b55434049b7ad59b17fc6a596 character varying(20),
    ca1f972f4de3489ab22a01969d48cf87 character varying(100),
    bb55a2f92921452694f59d8a8a1326d5 character varying(100),
    ddaa3d5555544e4189b778b33378a068 text,
    jeb5a5a44f584ced918daa63fc516d3a text,
    da763089b5a74afbb02caf6260fbd5f1 text,
    g01690cbd8cc49199cfa07bd592d8019 text,
    e10ba09257a94839884fc98626b906dc character varying(100),
    d9b6a0e29ad645c5a7b72d93d0fe1d47 character varying(100),
    cbf0d79ce6174a4d9d51253ff7378f73 character varying(100),
    f0d32c9c463943beabb62aee111dedd7 character varying(100),
    bc9c226e4b924d669888ee61a64403ef character varying(100),
    f698d75dbf9246299dfc500287e26db3 character varying(100),
    b403ff0d8f8f4246b38b60374141e5bd character varying(100),
    cc2480e3fe9e4e65bd4911b254055033 character varying(100),
    c774ea5e257840519a9e288f59b9b363 character(32),
    dd34eae45f8b4064aef0cdb83693b860 character(32),
    a2ab318732c646fcb3c53c659b102913 character(32),
    heed7bff76b5478eb40f0a27e48d2d96 character(32),
    e261a9b74bf34bfbb2a2961456ebe4d0 character varying(100),
    cd2bfcb5c3e2441b915609538f9fb286 character varying(100),
    gfe84d6fa81848d19f711815b8a3e22f numeric(18,2),
    is_imported smallint DEFAULT 0 NOT NULL,
    check_in_as_new_version smallint DEFAULT 0 NOT NULL,
    check_in_as_override_previous_content smallint DEFAULT 0 NOT NULL,
    cdabda50f9404a77a4c22dd774a6c838 character varying(100),
    gb4022b9cefc4b07b9958b8c73b2a17c character varying(95),
    h7e1bec9fed94c0d8deaeb02b94b48bb character varying(210),
    f1da51d24ef24be2979bda91ba8d59ac character varying(21),
    c94b3507b2094211af5c15b9674e24da character varying(20),
    bd3fe6ad0f694c88b811e295cd80c2db character varying(35),
    f80092a495454a4ab5a50d32cf6e8b74 character varying(20)
);

CREATE TABLE nodetype_d4fb23bf1402454c899d7c9ed7be14d2 (
    uid character(65) NOT NULL,
    acl_uid character(32),
    owner_uid character(32),
    classification_uid character(32),
    secondary_classification_uid character(32),
    tertiary_classification_uid character(32),
    record_number character varying(100),
    retention_schedule_uid character(32),
    hold_uid character(32),
    disposition_status integer,
    title character varying(255),
    combined_title text,
    description text,
    date_registered timestamp without time zone,
    creator_name character varying(255),
    creator_username character varying(255),
    notes text,
    home_uid character(32),
    assignee_uid character(32),
    is_finalized smallint,
    is_hybrid smallint DEFAULT 0,
    date_finalized timestamp without time zone,
    barcode character varying(50),
    external_barcode character varying(50),
    external_uid character varying(50),
    integrity_check text,
    security_level_uid character(32),
    date_last_modified timestamp without time zone,
    date_last_modified_of_contents timestamp without time zone,
    client_uid character(32),
    date_closed timestamp without time zone,
    next_enclosure_number integer DEFAULT 1 NOT NULL,
    enclosure_number_increment integer DEFAULT 1 NOT NULL,
    uncompressed_record_number character varying(100),
    security_based_on_container smallint DEFAULT 0,
    bypass_referenced_acls smallint DEFAULT 0,
    opened_temporarily smallint DEFAULT 0,
    date_created timestamp without time zone,
    author character varying(255),
    batch_id character varying(40),
    date_archived timestamp without time zone,
    date_made_inactive timestamp without time zone,
    date_of_last_enclosure timestamp without time zone,
    date_enclosed timestamp without time zone,
    record_class integer DEFAULT 0 NOT NULL,
    container_record_number character varying(50),
    classification_full_number character varying(255),
    secondary_classification_full_number character varying(255),
    tertiary_classification_full_number character varying(255),
    assignee_name character varying(255),
    home_name character varying(255),
    owner_name character varying(255),
    retention_schedule_number character varying(100),
    security_level_number smallint,
    client_name character varying(255),
    is_container_removed_on_ret_trig smallint DEFAULT 0,
    is_set_home_on_container_ret_trig smallint DEFAULT 0,
    retention_schedule_new_home character(32),
    is_misfiled smallint DEFAULT 0,
    master_uid character(65),
    hybrid_remarks text,
    date_last_modified_of_security_level timestamp without time zone,
    is_declassify smallint DEFAULT 0,
    is_imported smallint DEFAULT 0,
    enforce_single_creation_in_a_workflow smallint DEFAULT 0 NOT NULL,
    check_in_as_new_version smallint DEFAULT 0 NOT NULL,
    check_in_as_override_previous_content smallint DEFAULT 0 NOT NULL,
    is_declassify_alias text,
    is_auto_update_security_level smallint DEFAULT 0 NOT NULL,
    is_auto_update_security_level_on_particular_date smallint DEFAULT 0 NOT NULL,
    security_level_trigger_date timestamp without time zone,
    is_update_security_level_on_triggered_event smallint DEFAULT 0 NOT NULL,
    security_level_triggered_event integer DEFAULT 0,
    security_level_triggered_event_type integer DEFAULT 0,
    security_level_triggered_event_duration integer DEFAULT 0,
    security_level_triggered_event_property character(32),
    auto_update_security_level_id character(32),
    g4ffe1b80f4e474f92bc540863fd93b2 timestamp without time zone,
    da9a140784244810bf416ead6692b5f1 integer,
    ja187aff36f143088e12685ab403c800 character varying(100),
    jc7fa4a1003a43e79f261c8b6b85cb1b text
);

CREATE TABLE nodetype_fb160c57f6c849e1b1a3b3a40901b196 (
    uid character(65) NOT NULL,
    acl_uid character(32),
    owner_uid character(32),
    classification_uid character(32),
    secondary_classification_uid character(32),
    tertiary_classification_uid character(32),
    record_number character varying(50),
    retention_schedule_uid character(32),
    hold_uid character(32),
    disposition_status integer,
    title character varying(255),
    combined_title text,
    description text,
    date_registered timestamp without time zone,
    creator_name character varying(255),
    creator_username character varying(255),
    notes text,
    home_uid character(32),
    assignee_uid character(32),
    is_finalized smallint,
    is_hybrid smallint DEFAULT 0,
    date_finalized timestamp without time zone,
    barcode character varying(50),
    external_barcode character varying(50),
    external_uid character varying(50),
    integrity_check text,
    security_level_uid character(32),
    date_last_modified timestamp without time zone,
    date_last_modified_of_contents timestamp without time zone,
    client_uid character(32),
    date_closed timestamp without time zone,
    next_enclosure_number integer DEFAULT 1 NOT NULL,
    enclosure_number_increment integer DEFAULT 1 NOT NULL,
    uncompressed_record_number character varying(50),
    security_based_on_container smallint DEFAULT 0,
    bypass_referenced_acls smallint DEFAULT 0,
    opened_temporarily smallint DEFAULT 0,
    date_created timestamp without time zone,
    author character varying(255),
    batch_id character varying(40),
    date_archived timestamp without time zone,
    date_made_inactive timestamp without time zone,
    date_of_last_enclosure timestamp without time zone,
    date_enclosed timestamp without time zone,
    record_class integer DEFAULT 0 NOT NULL,
    container_record_number character varying(50),
    classification_full_number character varying(255),
    secondary_classification_full_number character varying(255),
    tertiary_classification_full_number character varying(255),
    assignee_name character varying(255),
    home_name character varying(255),
    owner_name character varying(255),
    retention_schedule_number character varying(100),
    security_level_number smallint,
    client_name character varying(255),
    is_container_removed_on_ret_trig smallint DEFAULT 0,
    is_set_home_on_container_ret_trig smallint DEFAULT 0,
    retention_schedule_new_home character(32),
    is_misfiled smallint DEFAULT 0,
    master_uid character(65),
    hybrid_remarks text,
    date_last_modified_of_security_level timestamp without time zone,
    is_declassify smallint DEFAULT 0,
    is_auto_update_security_level smallint DEFAULT 0 NOT NULL,
    is_auto_update_security_level_on_particular_date smallint DEFAULT 0 NOT NULL,
    security_level_trigger_date timestamp without time zone,
    is_update_security_level_on_triggered_event smallint DEFAULT 0 NOT NULL,
    security_level_triggered_event integer DEFAULT 0,
    security_level_triggered_event_type integer DEFAULT 0,
    security_level_triggered_event_duration integer DEFAULT 0,
    security_level_triggered_event_property character(32),
    auto_update_security_level_id character(32),
    h1bcd8ce6f7443538eda334170f71cc2 character varying(10),
    e8fb497b4b884d1a818ab307da1474eb character varying(100),
    g8a113b4b0854de6bb862a7bf714431d character varying(100),
    is_imported smallint DEFAULT 0 NOT NULL,
    check_in_as_new_version smallint DEFAULT 0 NOT NULL,
    check_in_as_override_previous_content smallint DEFAULT 0 NOT NULL,
    enforce_single_creation_in_a_workflow smallint DEFAULT 0 NOT NULL
);

CREATE TABLE nodetype_d967deb0a4c44739ac74466f7988d104 (
    uid character(65) NOT NULL,
    acl_uid character(32),
    owner_uid character(32),
    classification_uid character(32),
    secondary_classification_uid character(32),
    tertiary_classification_uid character(32),
    record_number character varying(50),
    retention_schedule_uid character(32),
    hold_uid character(32),
    disposition_status integer,
    title character varying(255),
    combined_title text,
    description text,
    date_registered timestamp without time zone,
    creator_name character varying(255),
    creator_username character varying(255),
    notes text,
    home_uid character(32),
    assignee_uid character(32),
    is_finalized smallint,
    is_hybrid smallint DEFAULT 0,
    date_finalized timestamp without time zone,
    barcode character varying(50),
    external_barcode character varying(50),
    external_uid character varying(50),
    integrity_check text,
    security_level_uid character(32),
    date_last_modified timestamp without time zone,
    date_last_modified_of_contents timestamp without time zone,
    client_uid character(32),
    date_closed timestamp without time zone,
    next_enclosure_number integer DEFAULT 1 NOT NULL,
    enclosure_number_increment integer DEFAULT 1 NOT NULL,
    uncompressed_record_number character varying(50),
    security_based_on_container smallint DEFAULT 0,
    bypass_referenced_acls smallint DEFAULT 0,
    opened_temporarily smallint DEFAULT 0,
    date_created timestamp without time zone,
    author character varying(255),
    batch_id character varying(40),
    date_archived timestamp without time zone,
    date_made_inactive timestamp without time zone,
    date_of_last_enclosure timestamp without time zone,
    date_enclosed timestamp without time zone,
    record_class integer DEFAULT 0 NOT NULL,
    container_record_number character varying(50),
    classification_full_number character varying(255),
    secondary_classification_full_number character varying(255),
    tertiary_classification_full_number character varying(255),
    assignee_name character varying(255),
    home_name character varying(255),
    owner_name character varying(255),
    retention_schedule_number character varying(100),
    security_level_number smallint,
    client_name character varying(255),
    is_container_removed_on_ret_trig smallint DEFAULT 0,
    is_set_home_on_container_ret_trig smallint DEFAULT 0,
    retention_schedule_new_home character(32),
    is_misfiled smallint DEFAULT 0,
    master_uid character(65),
    hybrid_remarks text,
    date_last_modified_of_security_level timestamp without time zone,
    is_declassify smallint DEFAULT 0,
    is_auto_update_security_level smallint DEFAULT 0 NOT NULL,
    is_auto_update_security_level_on_particular_date smallint DEFAULT 0 NOT NULL,
    security_level_trigger_date timestamp without time zone,
    is_update_security_level_on_triggered_event smallint DEFAULT 0 NOT NULL,
    security_level_triggered_event integer DEFAULT 0,
    security_level_triggered_event_type integer DEFAULT 0,
    security_level_triggered_event_duration integer DEFAULT 1,
    security_level_triggered_event_property character(32),
    auto_update_security_level_id character(32),
    enforce_single_creation_in_a_workflow smallint DEFAULT 0 NOT NULL,
    g7c2f72ba7cc44c18a07079c8f183418 character varying(100),
    is_imported smallint DEFAULT 0 NOT NULL,
    check_in_as_new_version smallint DEFAULT 0 NOT NULL,
    check_in_as_override_previous_content smallint DEFAULT 0 NOT NULL
);

CREATE TABLE profile (
    uid character(32) NOT NULL,
    name character varying(50) NOT NULL,
    p1000 smallint DEFAULT 0 NOT NULL,
    p1 smallint DEFAULT 0 NOT NULL,
    p11 smallint DEFAULT 0 NOT NULL,
    p21 smallint DEFAULT 0 NOT NULL,
    p41 smallint DEFAULT 0 NOT NULL,
    p42 smallint DEFAULT 0 NOT NULL,
    p51 smallint DEFAULT 0 NOT NULL,
    p52 smallint DEFAULT 0 NOT NULL,
    p53 smallint DEFAULT 0 NOT NULL,
    p54 smallint DEFAULT 0 NOT NULL,
    p61 smallint DEFAULT 0 NOT NULL,
    p71 smallint DEFAULT 0 NOT NULL,
    p81 smallint DEFAULT 0 NOT NULL,
    p91 smallint DEFAULT 0 NOT NULL,
    p92 smallint DEFAULT 0 NOT NULL,
    p93 smallint DEFAULT 0 NOT NULL,
    p94 smallint DEFAULT 0 NOT NULL,
    p95 smallint DEFAULT 0 NOT NULL,
    p100 smallint DEFAULT 0 NOT NULL,
    p101 smallint DEFAULT 0 NOT NULL,
    p102 smallint DEFAULT 0 NOT NULL,
    p103 smallint DEFAULT 0 NOT NULL,
    p111 smallint DEFAULT 0 NOT NULL,
    p112 smallint DEFAULT 0 NOT NULL,
    p121 smallint DEFAULT 0 NOT NULL,
    p122 smallint DEFAULT 0 NOT NULL,
    p123 smallint DEFAULT 0 NOT NULL,
    p2001 smallint DEFAULT 0 NOT NULL,
    p2002 smallint DEFAULT 0 NOT NULL,
    p2003 smallint DEFAULT 0 NOT NULL,
    p2005 smallint DEFAULT 0 NOT NULL,
    p2006 smallint DEFAULT 0 NOT NULL,
    p2007 smallint DEFAULT 0 NOT NULL,
    p2008 smallint DEFAULT 0 NOT NULL,
    p2009 smallint DEFAULT 0 NOT NULL,
    p2010 smallint DEFAULT 0 NOT NULL,
    p2011 smallint DEFAULT 0 NOT NULL,
    p2012 smallint DEFAULT 0 NOT NULL,
    p2013 smallint DEFAULT 0 NOT NULL,
    p2014 smallint DEFAULT 0 NOT NULL,
    p2015 smallint DEFAULT 0 NOT NULL,
    p2016 smallint DEFAULT 0 NOT NULL,
    p2017 smallint DEFAULT 0 NOT NULL,
    p2018 smallint DEFAULT 0 NOT NULL,
    p2019 smallint DEFAULT 0 NOT NULL,
    p2020 smallint DEFAULT 0 NOT NULL,
    p2021 smallint DEFAULT 0 NOT NULL,
    p2022 smallint DEFAULT 0 NOT NULL,
    p2023 smallint DEFAULT 0 NOT NULL,
    p2024 smallint DEFAULT 0 NOT NULL,
    p2025 smallint DEFAULT 0 NOT NULL,
    p2026 smallint DEFAULT 0 NOT NULL,
    p2027 smallint DEFAULT 0 NOT NULL,
    p2028 smallint DEFAULT 0 NOT NULL,
    p2029 smallint DEFAULT 0 NOT NULL,
    p3000 smallint DEFAULT 0 NOT NULL,
    p4000 smallint DEFAULT 0 NOT NULL,
    p5000 smallint DEFAULT 0 NOT NULL,
    p6000 smallint DEFAULT 0 NOT NULL,
    p6001 smallint DEFAULT 0 NOT NULL,
    p7000 smallint DEFAULT 0 NOT NULL,
    p8000 smallint DEFAULT 0 NOT NULL,
    p8001 smallint DEFAULT 0 NOT NULL,
    p9000 smallint DEFAULT 0 NOT NULL,
    p10000 smallint DEFAULT 0 NOT NULL,
    p11000 smallint DEFAULT 0 NOT NULL,
    p12000 smallint DEFAULT 0 NOT NULL,
    p13000 smallint DEFAULT 0 NOT NULL,
    p14000 smallint DEFAULT 0 NOT NULL,
    p15000 smallint DEFAULT 0 NOT NULL,
    p16000 smallint DEFAULT 0 NOT NULL,
    p17000 smallint DEFAULT 0 NOT NULL,
    p18000 smallint DEFAULT 0 NOT NULL,
    p19000 smallint DEFAULT 0 NOT NULL,
    p20000 smallint DEFAULT 0 NOT NULL,
    p21000 smallint DEFAULT 0 NOT NULL,
    p22000 smallint DEFAULT 0 NOT NULL,
    p23000 smallint DEFAULT 0 NOT NULL,
    p25000 smallint DEFAULT 0 NOT NULL,
    p26000 smallint DEFAULT 0 NOT NULL,
    p27000 smallint DEFAULT 0 NOT NULL,
    p28000 smallint DEFAULT 0 NOT NULL,
    p29000 smallint DEFAULT 0 NOT NULL,
    p30000 smallint DEFAULT 0 NOT NULL,
    p31000 smallint DEFAULT 0 NOT NULL,
    p40000 smallint DEFAULT 0 NOT NULL,
    p41000 smallint DEFAULT 0 NOT NULL,
    p42000 smallint DEFAULT 0 NOT NULL,
    p43000 smallint DEFAULT 0 NOT NULL
);

CREATE TABLE bankmastertable (
    bankcode character varying(10) NOT NULL,
    bankname character varying(60),
    bankabbreviation character varying(10),
    description text,
    e_mandate_settings smallint DEFAULT 1 NOT NULL
);

CREATE TABLE container_containee (
    container_uid character(65) NOT NULL,
    containee_uid character(65) NOT NULL,
    enclosure_number integer
);

CREATE TABLE esign_wflow (
    uid character(32) NOT NULL,
    node_uid character(65) NOT NULL,
    message text,
    status smallint DEFAULT 0 NOT NULL,
    esign_type smallint DEFAULT 0 NOT NULL,
    initiator_uid character(32) NOT NULL,
    abortion_reason text,
    esign binary,
    start_ts timestamp without time zone,
    end_ts timestamp without time zone,
    bank_type smallint DEFAULT 1 NOT NULL,
    use_guard_time smallint DEFAULT 0 NOT NULL
);

CREATE TABLE record_node (
    record_number character varying(50) NOT NULL,
    node_uid character(65) NOT NULL
);

CREATE TABLE hold_node (
    hold_uid character(32) NOT NULL,
    node_uid character(65) NOT NULL
);

CREATE TABLE hold (
    uid character(32) NOT NULL,
    name character varying(50) NOT NULL,
    acl_uid character(32),
    description character varying(255),
    active_from timestamp without time zone,
    active_to timestamp without time zone,
    contact_uid character(32),
    only_prevent_disposition_changes smallint
);

CREATE TABLE recent_container (
    uid character(32) NOT NULL,
    node_uid character(65) NOT NULL,
    action_timestamp timestamp without time zone NOT NULL,
    actor_uid character(32) NOT NULL,
    container_level integer NOT NULL
);

CREATE TABLE ftextindex (
    uid character(32) NOT NULL,
    insertion_timestamp timestamp without time zone NOT NULL,
    nodetype_id character(32) NOT NULL,
    node_id character(65) NOT NULL,
    index_code smallint DEFAULT 1 NOT NULL,
    target character(1) DEFAULT 'A',
    completion_status character(1) DEFAULT 'P',
    exception character varying(255),
    index_timestamp timestamp without time zone,
    completion_timestamp timestamp without time zone
);

CREATE TABLE evt_based_notification (
    uid character(32) NOT NULL,
    name character varying(50) NOT NULL,
    description character varying(255),
    acl_uid character(32),
    active_from timestamp without time zone,
    active_to timestamp without time zone,
    suspend smallint DEFAULT 0 NOT NULL,
    nodetype_uid character(32) NOT NULL,
    use_node_filter_script smallint DEFAULT 0 NOT NULL,
    node_filter_script text,
    notify_on_create_event smallint DEFAULT 0 NOT NULL,
    notify_on_change_event smallint DEFAULT 0 NOT NULL,
    notify_on_delete_event smallint DEFAULT 0 NOT NULL,
    urgent smallint DEFAULT 0 NOT NULL,
    send_as_bcc smallint DEFAULT 0 NOT NULL,
    email_template_uid character(32),
    recipients_email text,
    include_assignee smallint DEFAULT 0 NOT NULL,
    include_home smallint DEFAULT 0 NOT NULL,
    include_owner smallint DEFAULT 0 NOT NULL,
    include_members_of_group smallint DEFAULT 0 NOT NULL,
    group_uid character(32),
    include_principals_from_property smallint DEFAULT 0 NOT NULL,
    property_uid character(32),
    sender_email character varying(255),
    cc_email text,
    include_principals_from_propertycc smallint DEFAULT 0 NOT NULL,
    propertycc_uid character(32)
);

CREATE TABLE node_event (
    event_timestamp timestamp without time zone NOT NULL,
    event_type character varying(100) NOT NULL,
    node_uid character(65) NOT NULL,
    node_record_number character varying(50),
    node_title character varying(255) NOT NULL,
    principal_uid character(32) NOT NULL,
    principal_name character varying(255) NOT NULL,
    details text,
    ipaddress character varying(45)
);

CREATE TABLE object_event (
    event_timestamp timestamp without time zone NOT NULL,
    event_type character varying(100) NOT NULL,
    object_uid character(32) NOT NULL,
    object_type integer NOT NULL,
    object_name character varying(255) NOT NULL,
    principal_uid character(32) NOT NULL,
    principal_name character varying(255) NOT NULL,
    details text NOT NULL,
    ipaddress character varying(45)
);